# Generated by Django 4.2.2 on 2023-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='img/padrao.jpg', null=True, upload_to='img/produtos/%Y/'),
        ),
    ]
