# Generated by Django 4.2.2 on 2023-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='img/padrao.jpg', null=True, upload_to='produtos/%Y/'),
        ),
    ]
