# Generated by Django 4.2.2 on 2023-06-14 20:33

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='img/padrao.jpg', null=True, upload_to='produtos/%Y/'),
        ),
    ]
