# Generated by Django 4.2.2 on 2023-06-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_promocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='produto',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
