# Generated by Django 4.2.2 on 2023-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_carrinho_itemcarrinho_carrinho_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
