# Generated by Django 4.2.2 on 2023-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(),
        ),
    ]
